config/routes.rb
Rails.application.routes.draw do
  root 'mains#index'
  get 'mains/index'
  get 'sessions/new'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :mains do
    collection do
      post :confirm
    end
  end

  resources :users do
    collection do
    end
  end

  resources :sessions do
    collection do
    end
  end

  resources :favorites do
    collection do
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :main
end

app/models/main.rb
class Main < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many:mains
  has_many :favorites, dependent: :destroy
  has_many :favorite_mains, through: :favorites, source: :main
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
      favorite = current_user.favorites.create(main_id: params[:main_id])
      redirect_to mains_url, notice: "#{favorite.main.user.name}さんのブログをお気に入り登録しました"
    end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to mains_url, notice: "#{favorite.main.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
   before_action :set_main, only: [:show, :edit, :update, :destroy]
   before_action :user_only, only: [:new, :edit, :update, :destroy]

  def index
    @mains = Main.all
  end

  def edit
  end

  def confirm
    @main = Main.new(main_params)
    @main.user_id = current_user.id
    render :new if @main.invalid?
  end

  def update
    if @main.update(main_params)
      redirect_to mains_path, notice: "投稿を編集しました！"
    else
      render 'edit'
    end
  end

  def new
    if params[:back]
      @main = Main.new(main_params)
    else
      @main = Main.new
    end
  end

  def create
    @main = Main.new(main_params)
    @main.user_id = current_user.id
    @email = current_user.email
      if @main.save  
        redirect_to mains_path, notice: "投稿を作成しました！"
      else
        render 'new'
      end
  end

  def destroy
    @main.destroy
    redirect_to mains_path, notice:"投稿を削除しました！"
  end

  def show
    @favorite = current_user.favorites.find_by(main_id: @main.id)
  end

  private

  def main_params
    params.require(:main).permit(:comment, :image, :image_cache)
  end

  def set_main
    @main = Main.find(params[:id])
  end

  def user_only
    if logged_in?
    else
      redirect_to "/sessions/new"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user =User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites_mains = @user.favorite_mains
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to mains_path, notice: "変更しました！"
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/mains_helper.rb
module MainsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_mains_path
    elsif action_name == 'edit'
      main_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="top-header">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">Instagram Clone</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/mains/index">Instagram Clone</a>
          </div>
          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li>
                <div class="button_to_index">
                  <a href="/mains/new" class= "button_to_new">投稿</a>
                </div>
              </li>
              <li>
              <form class="navbar-form">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="">
                </div>
                <button type="submit" class="btn btn-info">検索</button>
              </form>
              </li>
              <% if logged_in? %>
              <li class="button_to_profile">
                <%= link_to "Profile", user_path(current_user.id) %>
              </li>
              <li class="button_to_logout">
                <%= link_to "Logout", session_path(current_user.id), method: :delete %>
              </li>
              <% else %>
              <li class="button_to_login">
                <%= link_to "Sign up / Log in", new_user_path %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </head>
  <body>
    <%= yield %>
  </body>
  <footer>
          <p>運営会社 OO 株式会社</p>
          <p>© 2018-2019 Copyright OO Inc.</p>
  </footer>
</html>

app/views/mains/_form.html.erb
<div class="container_fluid">
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <%= form_with(model: @main, local: true, url: choose_new_or_edit) do |form| %>
      <% if @main.errors.any? %>

        <div id="error_explanation">
          <h2><%= @main.errors.count %>件のエラーがあります。</h2>
          <ul>

            <% @main.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="blog_title">
        <%= form.label :コメント %>
        <%= form.text_field :comment %>
      </div>
      <div class="field">
        <%= form.label :image %>
        <!-- 確認画面から新規作成画面に戻った時に、 -->
        <!-- アップロードした画像を表示させるための記述 -->
        <%= image_tag(@main.image.url) if @main.image.url %>
        <%= form.file_field :image %>
        <%= form.hidden_field :image_cache %>

        <%= form.submit "投稿" %>
      <% end %>

      <%= link_to "一覧画面にもどる", mains_path %>
    </div>
  </div>
</div>

app/views/mains/confirm.html.erb
<div class="container_fluid">
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <h3>以下の内容で、送信する。</h3>
      <div class="main_confirm_post">
        <%= form_with(model: @main, url: mains_path, local: true) do |form| %>
        <%= form.hidden_field :comment %>
        <p>コメント:<%= @main.comment %></p>
        <%= image_tag(@main.image.url, :size => "250x250") if @main.image.url %>
        <%= form.hidden_field :image_cache %>
      </div>
      <div class="post_button">
        <%= form.submit "登録する" %>
      </div>
    <% end %>

    <%= form_with(model: @main, url: new_main_path, local: true, method: 'get') do |form| %>
    <%= form.hidden_field :comment %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "もどる", name: 'back' %>
  <% end %>

</div>
</div>
</div>

app/views/mains/edit.html.erb
<%= form_with(model: @main, local: true, url: main_path) do |form| %>

<% if @main.errors.any? %>
    <div id="error_explanation">
      <h2><%= @main.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @main.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form' %>
  
<% end %>

app/views/mains/index.html.erb
<div class="container_fluid">
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <p><%= notice %></p>
      <% @mains.each do |main| %>
        <div class="main_scroll">
          <div class="main_userinfo">
            <%= image_tag(main.user.image.url, :size => "50x50") %>
            <%= main.user.name %>
          </div>
          <p>
            <%= image_tag(main.image.url, :size => "300x300") %>
          </p>
          <p class="main_comment">
            <%= main.comment %>
          </p>
          <tr>
            <td><%= link_to '詳細', main_path(main.id) %></td>
              <% if logged_in? %>
                <% if current_user.id == main.user_id %>
                  <td><%= link_to "編集", edit_main_path(main.id) %></td>
                  <td><%= link_to '削除', main_path(main.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
                  <% else %>
                <% end %>
              <% else %>
            <% end %>    
          </tr>
        </div>
      <% end %>
      <h4 class="go-top">↑Topへ戻る</h4>
    </div>
  </div>
</div>

app/views/mains/new.html.erb
<h2>投稿する</h2>
<%= render 'form' %>

app/views/mains/show.html.erb
<h1>詳細画面</h1>
<p>コメント: <%= @main.comment %></p>
<% if @main.image.present? %>
<p>
  <%= image_tag(@main.image.url, :size => "250x250") %>
</p>
<% end %>
<% unless @main.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(main_id: @main.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", mains_path %>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true, url: user_path) do |form| %>

<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with(model: @user, local: true, url: user_path) do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </p>
    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </p>
    <p>
      <%= f.label :image %>
      <!-- 確認画面から新規作成画面に戻った時に、 -->
      <!-- アップロードした画像を表示させるための記述 -->
      <%= image_tag(@user.image.url) if @user.image.url %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
      <%= f.submit "変更する" %>
    </p>
  <% end %>
<% end %>

app/views/users/new.html.erb
<html>
  <body>
    <div class ="container-fluid">
      <div class ="row_E">
        <div class ="col-sm-12 col-md-offset-2 col-md-8">
          <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
              <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
      <div class ="row_F">
        <div class="col-sm-6 col-md-offset-4 col-md-2">
          <h1><%= link_to "Sign up", new_user_path %></h1>
        </div>
        <div class="col-sm-6 col-md-2">
          <h1><%= link_to "Login", new_session_path %></h1>
        </div>
      </div>
      <div class ="row_G">
        <div class="col-sm-12 col-md-offset-4 col-md-4">
          <%= form_with(model: @user, local: true) do |f| %>
            <p>
              <%= f.label :name %><br>
              <%= f.text_field :name %>
            </p>
            <p>
              <%= f.label :email %><br>
              <%= f.email_field :email %>
            </p>
            <p>
              <%= f.label :password %><br>
              <%= f.password_field :password %>
            </p>
            <p>
              <%= f.label :password_confirmation %><br>
              <%= f.password_field :password_confirmation %>
            </p>
            <p>
              <%= f.label :image %>
              <!-- 確認画面から新規作成画面に戻った時に、 -->
              <!-- アップロードした画像を表示させるための記述 -->
              <%= image_tag(@user.image.url) if @user.image.url %>
              <%= f.file_field :image %>
              <%= f.hidden_field :image_cache %>
              <%= f.submit "Create my account" %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<html>
  <body>
    <div class="container">
      <div class="row_I">
        <div class="col-md-offset-2 col-md-10">
          <div class="row_K">
            <div class="col-md-3">
              <div class="userpage_icon">
                <%= image_tag(@user.image.url, :size => "50x50") %>
              </div>
            </div>
            <div class="col-md-9">
              <div class="userpage_title">
              <h1><%= @user.name %>のページ</h1>
              <p>メールアドレス: <%= @user.email %></p>
              <p><%= link_to "編集する", edit_user_path %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="row_J">
        <p>お気に入り一覧</p>
        <% @favorites_mains.each do |favorite_main| %>
        <div class="col-sm-12 col-md-12">
          <div class="favoritelist_right">
            <p><%= favorite_main.comment %></p>
            <p><%= favorite_main.user.name %></p>
            <%= image_tag(favorite_main.image.url, :size => "150x150") %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </body>
</html>